

seed: 42
batch_size: 4
max_device_batch_size: 512
base_learning_rate: 0.00015
weight_decay: 0.05
mask_ratio: 0.25
total_epoch: 10
warmup_epoch: 1
model_path: vit-t-mae.pt
patch_size: 4
n_mels: 80
audio_filename: gapped_audio.wav
test_audio_filename: wav_test.wav
emb_dim: 192
encoder_layer: 12
encoder_head: 3
decoder_layer: 4
decoder_head: 3